#Protocol

[http]
name = "http"
port = 80
info = "jhsfjshflkhsdqfljshlfkhj"

[https]
name = "https"
port = 443
info = "jhsfjshflkhsdqfljshlfkhj"

[ftp]
name = "ftp"
port = 21
info = "jhsfjshflkhsdqfljshlfkhj"

[ssh]
name = "ssh"
port = 22
info = "jhsfjshflkhsdqfljshlfkhj"