#!/bin/bash

######################################
# cheats_update
# Description : Mise à jour des cheats navi
# Auteur: Zami3l
######################################

PATH_CHEATS='/root/.local/share/navi/cheats/'

echo -e "\n=> Démarrage de la mise à jour des cheatsheets...\n"
cd $PATH_CHEATS && git pull &> /dev/null 
echo -e "=> Mise à jour terminée. \n"