#!/bin/bash

######################################
# run
# Description : Permet d'exécuter plusieurs actions pour les cheatsheets 
# Auteur: Zami3l
######################################

main () {

    action="${1}"
    cmd="${@:2}"

    if [ ${action} = "view" ]; then
        fView ${cmd}
    elif [ ${action} = "exec" ]; then
        fExec ${cmd}
    fi

}

fView () {
    echo ${@}
}

fExec () {
    echo "--> ${@}" && eval ${@}
}

main ${@}